import Head from 'next/head';
import axios from 'axios';
import styles from '@/styles/Home.module.css'
import TableUsers from '@/components/Table/tableUsers/TableUsers'



function Home({ dataUsers }) {

  return (
    <>
      <Head>
        <title>Users Table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.titlePage}>Table Users Challenge</h1>
        <TableUsers dataUsers={dataUsers} />        
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const { data } = await axios.get('https://dummyjson.com/users?limit=100');
  return { props: { 
      dataUsers: data.users 
    }
  }
}

export default Home;